paths:
  config_dir: "config"
  data_dir: "data"
  metadata_file: "config/metadata.yaml"
  project_home: null
setting:
  initialized: false
  debug_mode: true
Catalog:
  csv_: false
  postgres_: false
Warehousing:
  InProd: false